/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2023-05-04 10:29:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Classic Register Form Responsive Widget Template ::\r\n");
      out.write("	w3layouts</title>\r\n");
      out.write("<!-- Meta tag Keywords -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("	content=\"Classic Register Form Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements\" />\r\n");
      out.write("<script>\r\n");
      out.write("	addEventListener(\"load\", function() {\r\n");
      out.write("		setTimeout(hideURLbar, 0);\r\n");
      out.write("	}, false);\r\n");
      out.write("\r\n");
      out.write("	function hideURLbar() {\r\n");
      out.write("		window.scrollTo(0, 1);\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Meta tag Keywords -->\r\n");
      out.write("<!-- css files -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- Style-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.css\">\r\n");
      out.write("<!-- Font-Awesome-Icons-CSS -->\r\n");
      out.write("<!-- //css files -->\r\n");
      out.write("<!-- web-fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- //web-fonts -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!--header-->\r\n");
      out.write("	<h1>\r\n");
      out.write("		<span>S</span>HOPPY<span>K</span>ART\r\n");
      out.write("	</h1>\r\n");
      out.write("	<!--//header-->\r\n");
      out.write("	<!-- content -->\r\n");
      out.write("	<div class=\"main-content-agile\">\r\n");
      out.write("		<div class=\"sub-main-w3\">\r\n");
      out.write("			<form action=\"#\" method=\"post\">\r\n");
      out.write("				<div class=\"form-style-agile\">\r\n");
      out.write("					<label>Your Name</label>\r\n");
      out.write("					<div class=\"pom-agile\">\r\n");
      out.write("						<input placeholder=\"Your Name\" name=\"Name\" type=\"text\" required=\"\">\r\n");
      out.write("						<span class=\"fa fa-user-o\" aria-hidden=\"true\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-style-agile\">\r\n");
      out.write("					<label>Email</label>\r\n");
      out.write("					<div class=\"pom-agile\">\r\n");
      out.write("						<input placeholder=\"Email\" name=\"Email\" type=\"email\" required=\"\">\r\n");
      out.write("						<span class=\"fa fa-envelope\" aria-hidden=\"true\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-style-agile\">\r\n");
      out.write("					<label>Password</label>\r\n");
      out.write("					<div class=\"pom-agile\">\r\n");
      out.write("						<input placeholder=\"Password\" name=\"Password\" type=\"password\"\r\n");
      out.write("							id=\"password1\" required=\"\"> <span class=\"fa fa-key\"\r\n");
      out.write("							aria-hidden=\"true\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-style-agile\">\r\n");
      out.write("					<label>Confirm Password</label>\r\n");
      out.write("					<div class=\"pom-agile\">\r\n");
      out.write("						<input placeholder=\"Confirm Password\" name=\"Confirm Password\"\r\n");
      out.write("							type=\"password\" id=\"password2\" required=\"\"> <span\r\n");
      out.write("							class=\"fa fa-key\" aria-hidden=\"true\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sub-agile\">\r\n");
      out.write("					<input type=\"checkbox\" id=\"brand1\" value=\"\"> <label\r\n");
      out.write("						for=\"brand1\"> <span></span>I Accept to the Terms &\r\n");
      out.write("						Conditions\r\n");
      out.write("					</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clear\"></div>\r\n");
      out.write("				<input type=\"submit\" value=\"Register\">\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //content -->\r\n");
      out.write("	<!--footer-->\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<h2>\r\n");
      out.write("			&copy; 2018 Classic Register Form. All rights reserved | Design by <a\r\n");
      out.write("				href=\"http://w3layouts.com\">W3layouts</a>\r\n");
      out.write("		</h2>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--//footer-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- password-script -->\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = function() {\r\n");
      out.write("			document.getElementById(\"password1\").onchange = validatePassword;\r\n");
      out.write("			document.getElementById(\"password2\").onchange = validatePassword;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function validatePassword() {\r\n");
      out.write("			var pass2 = document.getElementById(\"password2\").value;\r\n");
      out.write("			var pass1 = document.getElementById(\"password1\").value;\r\n");
      out.write("			if (pass1 != pass2)\r\n");
      out.write("				document.getElementById(\"password2\").setCustomValidity(\r\n");
      out.write("						\"Passwords Don't Match\");\r\n");
      out.write("			else\r\n");
      out.write("				document.getElementById(\"password2\").setCustomValidity('');\r\n");
      out.write("			//empty string means no validation error\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- //password-script -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
